apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.frontendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.frontendSelectorLabels" . | nindent 4 }}
